### ISSUE TITLE
BACK TO HOME_PAGE BUTTON

### ISSUE THREAD

**Issue by JeremM9** [myfavoritesubjectipt2/BSIT-WMA-4C_G1#8]
DUE TO DIFFERENT SCHEDULES AND WORK IN LIFE, THE **BACK BUTTON** IS NOT IMPLEMENTED IN EVERY PORTFOLIO. SO WHEN YOU CLICK EACH MEMBER'S PROFILE THERE IS NO BACK BUTTON TO BE PRESSED TO CHANGE THE PORTFOLIO TO VIEW.

**Comment by myfavoritesubjectipt2** [comment]
I already fixed it
